import React from 'react';
import Paper from 'material-ui/Paper';


export default class TermsComponent extends React.Component {

  render() {
    return (
      <div style={{ width: '100%', margin: 'auto' }}>
        <Paper zDepth={2} style={{ width: '80%', padding: '1.5rem', margin: 'auto', display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
          <h2 style={{ fontSize: '2.5rem', fontFamily: 'Lato' }}>Terms of Use</h2>
          <br />
          <p style={{ fontWeight: '600', fontSize: '1.5rem', fontFamily: 'Lato' }}>
              Last Updated: September 1, 2016
          </p>
          <p style={{ fontSize: '1rem', fontFamily: 'Lato' }}>
              These terms and conditions (“Terms of Use”), apply to the entire contents of the Websites under the domain names www.OpenCastings.com, and www.Toptalentcasting.com (the “Websites”), including any functionality and services offered on or through each of the Websites, and to any correspondence by Open Castings, LLC, a Delaware limited liability company (together with its owners, parents, subsidiaries, affiliates, directors, officers, managers, members agents and employees, “Open Castings”), you and any other users of the Websites (individually, a “User”, and collectively, “Users”). Please read these terms and conditions carefully before using the Websites. Please also review our Privacy Policy, which also governs your visit to the Websites, to understand our privacy practices.
          </p>
          <p style={{ fontSize: '1rem', fontFamily: 'Lato' }}>
              1. Introduction and Acceptance of Terms of Use.
          </p>
          <p style={{ fontSize: '0.75rem', fontFamily: 'Lato' }}>
              By visiting or using any of the Websites, including access or use through a computer, mobile device or mobile application, you accept and agree to be bound by these Terms of Use regardless of whether or not you choose to register with us.  If you do not accept these terms and conditions, do not use the Websites.
              You affirm that you are either more than eighteen (18) years of age, or an emancipated minor, or possess legal parental or guardian consent, and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms of Use, and to abide by and comply with these Terms of Use, and are not a person barred from using the Websites under the laws of the United States or other applicable jurisdiction.
              Users under the age of thirteen (13) who would like to participate in any of the Websites (a “Young User”), must have their parent or legal guardian (a “Parent Registered User)  register to use the Websites, using the Parent Registered User's name, email, and credit card information, and consent to a Young Users use of the Websites. Parent Registered Users are responsible  for updating the settings of and terminating their account and thereby use of the Websites by the applicable Young User.
              For purposes of these Terms of Use, Parent Registered Users and their Young Users are deemed to be Users as used in these Terms of Use. By registering as a Parent Registered User, you hereby represent, warrant, understand, agree to and accept these Terms of Use and any applicable additional terms in their entirety on behalf of yourself and your Young User whether or not you use any of the Websites. You further understand and agree that you will ensure your Young User’s compliance with these Terms of Use and that you are responsible for any noncompliance by your Young User.
              If you are a Parent Registered User, you also agree that you are responsible for monitoring the account of your Young User as well as your Young User’s activities both on and off of the Websites, including monitoring who your Young User communicates with and meets both on and off the Websites. When a Young User turns eighteen (18) years old, the Parent Registered User may transfer the account to their child, by changing the account name, email address, and credit card number on file in the account, if they so wish.
              If a parent or guardian believes that any Website has collected information of a child under the age of thirteen (13) without proper consent, please contact Open Castings at legal@OpenCastings.com.
              Open Castings may revise and update these Terms of Use from time to time in our sole discretion. All changes are effective immediately when we post them, and apply to all access to and use of the Websites thereafter. However, any changes to the dispute resolution provisions set forth in Governing Law and Jurisdiction section will not apply to any disputes for which the parties have actual notice on or prior to the date the change is posted on the Websites. Your continued use of the Websites following the posting of revised Terms of Use means that you accept and agree to the changes. You are expected to check this page so you are aware of any changes, as they are binding on you.
          </p>
          <br />
          <p style={{ fontSize: '1rem', fontFamily: 'Lato' }}>
              2. Website Content and Paid Services.
          </p>
          <br />
          <p style={{ fontSize: '0.75rem', fontFamily: 'Lato' }}>
              The Websites contain content including but not limited to text, graphics, photographs, images, news reports, articles, editorial and other writings, audio and video recordings, data, listings, and directory information (collectively, "Content") that is accessible by Users.  The Websites may also offer forums, bulletin boards, wikis, chat rooms, blogs or other interactive areas for Users to communicate with each other.  The creation of a user account may be required for the use of certain portions of the Websites.  In addition, certain contents and services of the Websites may only be accessed through purchase or paid subscription.  We refer to the paid services available on or through the Websites, including the digital and print publication subscription services, collectively as the "Paid Services".  Content that is available to Users only through purchase or paid subscription is referred to collectively as the "Paid Services Content". Content may include facts, views, opinions and recommendations of individuals and organizations not affiliated with Open Castings.  Open Castings does not guarantee the accuracy, completeness or timeliness of, or otherwise endorse, these facts, views, opinions or recommendations.

              Video auditions

              Open Castings offers services in which you may be invited to participate in video auditions.  All of the video auditions created through Open Castings services remain confidential with the Casting Customers  for whom you auditioned unless specified by the Actor.
              One-Way audition
              A One-Way audition involves an actor recording on their own time through Open Castings application or website to questions presented to them by Open Castings and Casting Customer
              Open audition
              An Open audition is similar to an One-Way audition except that an Casting Customers can send you a link through which you can self-register for an Open audition.

              If you choose to participate in an One-Way audition using a webcam and microphone, you authorize Open Castings to record the audition.  You also authorize Open Castings to allow the Casting Customers  for whom you completed the audition to see and listen to the recorded audition. Finally, you authorize Open Castings to store each recorded audition on its servers.
              Apart from Open Castings, only the Casting Customers  with and/or for whom you have auditioned will have access to any particular recorded Video audition.  As an actor, you cannot access any recorded Video auditions unless authorized or provided by Open Castings.
              Apart from the Casting Customers  with and/or for whom you have auditioned, Open Castings will not share or provide access to Video auditions to any third party absent a subpoena, court order or permission from recorded actor.  And, should Open Castings ever be subpoenaed for content associated with your Account, Open Castings shall provide you notice and an opportunity to file a motion objecting to any disclosure.
              As an actor, you may not create your own recordings of any Video auditions.  You authorize Open Castings to employ reasonable measures to prevent unauthorized recording of Video auditions.  Any effort to circumvent such measures shall be a violation of these Terms of Use.
              In addition to Video auditions, Casting Agencies and Casting Directors will be able to produce Welcome Videos for targeted actor Customers to view.
              Open Castings may add additional types of video content from time to time.


              3.5 No Guarantees of Employment
              Open Castings is not an employment agency.  Open Castings does not make any representations as to the qualifications of any individual, entity or casting.
              Additionally, where an individual, entity, group or casting successfully secures employment, Open Castings makes no guarantees or representations as to the satisfaction of such employment.
              Additionally, Open Castings does not guarantee that any individual or entity will find employment or an employee through Open Castings Services.

              3.6 Deletion of Content.  Except as provided elsewhere in these Terms of Use, all Customer Content and Video Content will no longer be accessible to you upon deletion or termination of your Account.

              3.7 Intentionally Omitted.

              3. Proprietary Rights.
              Open Castings owns, operates, licenses, controls, and provides access to the Websites. You acknowledge and agree that Open Castings, and its licensors, retain all right, title and interest in and to all past, present and future Content, excluding User Provided Content (as defined below), applications, software, content and materials provided on or through the Websites (including, without limitation, the audiovisual works, text, images, photographs, videos, graphics, page headers, editorial and contextual information, the selection and arrangement of elements displayed on or through the Websites, the compilation of all content and materials on the Websites, and the business process, procedures, methods and techniques used in the Websites) and all associated patent rights, copyright rights, trademark rights, trade secret rights and other intellectual property and proprietary rights recognized anywhere in the world.
              Open Castings, the Open Castings logo, actorfest, the actorfest logo, audition update and the audition update logo are the registered or common law or trademarks of Open Castings, LLC, and all other proprietary trademarks, service marks, trade names, trade dress, slogans, logos, and other indicia of origin that appear on or in connection with the Websites are the property of Open Castings, LLC unless otherwise noted and are protected by applicable copyright, trademark, intellectual property and other laws. Open Castings' intellectual property, including, without limitation, its trademarks and trade dress, may not be used in any manner that is likely to cause confusion among users, or in any manner that disparages Open Castings. All rights are expressly reserved.
              All third party trademarks, logos, photographs, images, audio and audio-visual content, programming, and other intellectual property contained on or within the Websites are the property of the respective third parties, including the respective Content owners, and may be protected by applicable copyright, trademark or other intellectual property laws and treaties. Each such third party expressly reserves all rights into such intellectual property. Use of third party software or services is subject to the terms and conditions of the applicable third party license agreements, and you agree to look solely to the applicable third party and not to Open Castings to enforce any of your rights in relation there to. Except as expressly set forth in these Terms of Use or otherwise expressly granted to you in writing by Open Castings, no rights (either by implication, estoppel or otherwise) in or to the Websites or their contents are granted to you.
              4. User Provided Content.
              Portions of the Websites may allow you and other Users to upload or transmit data, information, text, images, software, audio, photographs, graphics, video, messages, tags, or other materials to or through the Websites ("User Provided Content"). For example, the Websites may offer forums, bulletin boards, wikis, chat rooms, blogs or other interactive areas.  For User Provided Content, Open Castings is merely hosting and providing access.
              The decision to submit User Provided Content to the Websites is your responsibility and you should only submit content that belongs to you or that will not violate the rights of others. By submitting User Provided Content, you represent, acknowledge, and warrant (a) that you have the right to do so or that you have obtained any necessary third party consents (e.g., under privacy or intellectual property laws), (b) that the User Provided Content does not infringe on the copyrights, trademarks, moral rights, rights of privacy or publicity, or the intellectual property rights of any person or entity, and (c) that no other party has any right, title, claim, or interest in the User Provided Content that would be infringed upon as a result of uploading the User Provided Content. If you submit User Provided Content to the Websites on behalf of a group, organization or business entity, you represent that you have the right to do so and that you have obtained any consents from the group, organization or business. Upon the request of Open Castings, you agree to furnish Open Castings with any documentation, substantiation and releases necessary and reasonably required to verify and substantiate your compliance with this provision. You agree not to accept payment for User Provided Content from any third party, including, without limitation, accepting payment for the inclusion of a logo, brand advertising or other commercial content, in User Provided Content.
              Open Castings cannot vouch for the validity, accuracy or credibility of any User Provided Content, and does not take any responsibility or assume any liability for any actions Users may take as a result of viewing, reading or listening to User Provided Content on the Websites.  Through your use of the Websites you may be exposed to Content that you may find offensive, objectionable, harmful, inaccurate or deceptive. There may also be risks of dealing with underage persons, people acting under false pretenses, international trade issues and foreign nationals. Open Castings does not endorse any User Provided Content or any opinion, recommendation, or advice expressed therein. By using the Websites, you assume all associated risks, and Open Castings expressly disclaims any and all liability in connection with User Provided Content.
              In addition, you grant to Open Castings, without any credit or compensation to you, a royalty-free, non-exclusive, worldwide, perpetual, unrestricted, irrevocable, and fully transferable, assignable and sub-licensable license to host, use, modify, display, copy, reproduce, disclose, sell, translate, create derivative works of, distribute, and export any User Provided Content, in whole or in part, or to incorporate it in other works in any form, media, software or technology of any kind now known or hereafter developed or discovered for any purposes whatsoever. You agree that Open Castings may publish or otherwise disclose your name in connection with your User Provided Content.
              You acknowledge, consent and agree that Open Castings may access, preserve and disclose account information and User Provided Content that you provide if Open Castings is required to do so by law or if it believes in good faith that such access, preservation or disclosure is reasonably necessary to (i) comply with legal process, (ii) enforce these Terms of Use, (iii) respond to claims that any User Provided Content violates the rights of third parties, (iv) respond to your requests for customer service, or (v) protect the rights, property or personal safety of Open Castings, its employees, partners and agents or members of the public.
              Open Castings undertakes no obligation to pre-screen User Provided Content, but reserves the right to, and may from time to time, monitor any and all information transmitted or received through the Websites. You acknowledge, consent and agree that Open Castings, at its sole discretion and without notice to you, may review, censor, delete, move, edit, block access to or prohibit the transmission or receipt of any User Provided Content or other information, in whole or in part, that Open Castings deems obscene, defamatory or libelous in nature, that invades the right of privacy or infringes any right of any person or entity, is unlawful, is offensive or otherwise inappropriate, or that Open Castings believes to be in violation of these Terms of Use.
              You are solely responsible for all User Provided Content that you make available via the Websites. Under no circumstances will Open Castings be liable to you in any way for any User Provided Content that you upload, post, or otherwise make available via the Websites including, but not limited to, any errors or omissions in User Provided Content, or for any loss or damage of any kind incurred as a result of User Provided Content. In addition, you hereby release Open Castings from any and all claims, liens, demands, actions or suits in connection with the User Provided Content, including, without limitation, any and all liability for any use or nonuse of your User Provided Content, claims for defamation, invasion of privacy, right of publicity, emotional distress or economic loss. Except for the rights granted in these Terms of Use, Open Castings acquires no title or ownership rights in or to any User Provided Content you submit and nothing in these Terms of Use conveys any ownership rights in the User Provided Content you submit to Open Castings.
              5. Third Party Content and Linked Sites.
              Third parties provide some of the Content of the Websites. Open Castings makes no representations or warranties as to the completeness, accuracy, adequacy, currency or reliability of any content supplied by third parties and will not be liable for any lack of the foregoing or for any errors or omissions in any content supplied by third parties. In addition, third parties may offer goods, services and other materials to you on the Websites. Such dealings are solely between you and the third party. Open Castings will not be responsible for any loss or damage of any sort incurred as the result of any such dealings. Open Castings makes no warranty concerning, is not responsible for and does not endorse any third party provided goods or services, and you agree that any recourse for dissatisfaction or problems with those goods or services will be sought from the third party provider and not from Open Castings.
              Descriptions of, or references to products, services or publications within the Websites do not imply endorsement by Open Castings of that product, service or publication. The Websites may include links to other sites that are not maintained by Open Castings. Websites of those third parties are subject to terms and conditions different from those found here and it is your responsibility to ensure that you have read and understood them. Open Castings is not responsible for the content of those sites, does not endorse those sites, and makes no representations whatsoever concerning the content or accuracy of such other sites. If you decide to access any third party site linked to the Websites, you do so entirely at your own risk, and you may be exposed to offensive, indecent or objectionable content. Open Castings shall have no liability for any loss or damage arising from your use of any such sites.
              6. Limited License.
              Subject to your compliance with these Terms of Use, Open Castings grants you a limited, personal, non-exclusive, non-commercial, revocable, non-assignable and non-transferable license to:
              View and listen to the Content contained on the Websites;
              Create profile pages on the Websites for non-commercial and private use;
              Participate in the Websites' community areas and communicate with other Users; and
              Download the Content contained on the Websites onto a computer or other personal electronic device for your personal, non-commercial home or archival use only, provided you do not delete or change any copyright, trademark, or other proprietary notices contained therein.
              In addition to the foregoing, by subscribing to the Paid Services, Open Castings grants you a personal, limited non-exclusive, non-transferable and non-assignable license to access and use the Paid Services Content. You may not use the Paid Services Content for development of data-related products or services, the creation of any database product, or for data provision services. Unless separately and specifically licensed to do so in writing by Open Castings, you agree not to re-transmit, disclose or distribute any Paid Services Content to any other person, organization or entity. You expressly agree that the Paid Services and Paid Services Content shall be used solely for your own benefit and that the Paid Services Content (including print publications, if applicable) shall not be redistributed or republished by you. You understand and agree that the features of the Paid Services are subject to change without notice to you.
              You may not take any action to jeopardize, limit or interfere with Open Castings' ownership of and rights with respect to the Websites or any Content.  The use, copying, sale, leasing, renting, lending, distribution, modification, downloading, creating of derivative works, posting or publication by you, directly or indirectly, of any Content, or any other use of such Content, except pursuant to the foregoing express limited grant of rights, is strictly prohibited.  Bots, crawlers, spiders, data miners, scraping and any other automatic access tool are expressly prohibited. You acknowledge that any unauthorized copying or unauthorized use of the Websites or of any Content is a violation of these Terms of Use and is strictly prohibited. Violation of this limited use license may result in immediate termination of your access and use of the Websites and may result in legal action against you.
              7. Restrictions on Use.
              The Websites is provided for lawful purposes only. By accessing or using the Websites, you agree and warrant that in connection with your use of the Websites you will not:
              alter any trademark, copyright and other proprietary or legal notices contained in the Websites; or
              manipulate the Websites in any way not intended and directed by Open Castings; or
              copy or seek to copy or "rip" any audio, video or audiovisual content from the Websites; or
              exploit any part of the Websites for commercial gain or undertake any commercial activity utilizing the contents of the Websites without the prior written consent of Open Castings, including, for example, inserting your own or a third party's advertising, branding or promotional content into the Websites’ contents, materials or services; or
              upload, post, e-mail, transmit, display, copy, distribute, promote, or otherwise communicate to the public:
              any material that is false, unlawful, threatening, tortious, disparaging, abusive, libelous, defamatory, obscene, vulgar, offensive, pornographic, profane, racist, sexually explicit, ethnically or culturally offensive, indecent, harassing, or that promotes violence, racial hatred, terrorism, or illegal acts, or anything that in Open Castings' sole discretion is otherwise objectionable; or
              information, software, content or other material that violates, plagiarizes, misappropriates or infringes the rights of third parties including, without limitation, copyright, trademark, patent, trade secret, rights of privacy or publicity, confidential information or any other proprietary right; or
              material of any kind that restricts or inhibits any other user's uninhibited use and enjoyment of the Websites or interferes with, overburdens, impairs or disrupts the Websites, including material that contains a virus, Trojan horse, time bomb, worm, spyware, adware, malware, bot, any automated system, such as scripts, or any other harmful component; or
              any unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes, requests for money, petitions for signature, or any other form of solicitation; or
              use or attempt to use another person's information, account, password, service or system except as expressly permitted; or
              impersonate another person or entity; or
              engage in any conduct that in Open Castings 's sole discretion restricts the ability of any other person to enjoy the use of the Websites; or
              solicit or collect personal data including telephone numbers, addresses, last names, email addresses, or any other kind of information about users.
              8. Copyright Notices and Celebrity Material Infringement.
              Copyright Notices/Complaints
              Open Castings takes claims of copyright infringement seriously.  We will respond to notices of alleged copyright infringement that comply with applicable law.  If you believe any materials accessible on or from the Websites infringe your copyright, you may request removal of those materials (or access to them) from the Websites by submitting written notification to our Copyright Agent (designated below). In accordance with the Online Copyright Infringement Liability Limitation Act of the Digital Millennium Copyright Act (17 U.S.C. § 512) ("DMCA"), the written notice (the "DMCA Notice") must include substantially the following:
              Your physical or electronic signature.
              Identification of the copyrighted work you believe to have been infringed or, if the claim involves multiple works on the Websites, a representative list of such works.
              Identification of the material you believe to be infringing in a sufficiently precise manner to allow us to locate that material.
              Adequate information by which we can contact you (including your name, postal address, telephone number and, if available, e-mail address).
              A statement that you have a good faith belief that use of the copyrighted material is not authorized by the copyright owner, its agent or the law.
              A statement that the information in the written notice is accurate.
              A statement, under penalty of perjury, that you are authorized to act on behalf of the copyright owner.
              Our designated Copyright Agent to receive DMCA Notices is:
              Open Castings, LLC
                    Attn: General Counsel's Office
                      45 Main St.
                      Brooklyn, NY 11201
              212.493.4243
              legal@opencastings.com
              If you fail to comply with all of the requirements of Section 512(c)(3) of the DMCA, your DMCA Notice may not be effective. Please be aware that if you knowingly materially misrepresent that material or activity on the Websites is infringing your copyright, you may be held liable for damages (including costs and attorneys' fees) under Section 512(f) of the DMCA.
              If you believe that material you posted on the Websites was removed or access to it was disabled by mistake or misidentification, you may file a counter-notification with us (a "Counter-Notice") by submitting written notification to our copyright agent (identified below). Pursuant to the DMCA, the Counter-Notice must include substantially the following:
              Your physical or electronic signature.
              An identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access disabled.
              Adequate information by which we can contact you (including your name, postal address, telephone number and, if available, e-mail address).
              A statement under penalty of perjury by you that you have a good faith belief that the material identified above was removed or disabled as a result of a mistake or misidentification of the material to be removed or disabled.
              A statement that you will consent to the jurisdiction of the Federal District Court for the judicial district in which your address is located (or if you reside outside the United States for any judicial district in which the Websites may be found) and that you will accept service from the person (or an agent of that person) who provided the Websites with the complaint at issue.
              Completed Counter-Notices should be sent to:
              Open Castings, LLC
                    Attn: General Counsel's Office
                      45 Main St.
                      Brooklyn, NY 11201
              212.493.4243
              legal@opencastings.com
              The DMCA allows us to restore the removed content if the party filing the original DMCA Notice does not file a court action against you within ten business days of receiving the copy of your Counter-Notice. Please be aware that if you knowingly materially misrepresent that material or activity on the Websites was removed or disabled by mistake or misidentification, you may be held liable for damages (including costs and attorneys' fees) under Section 512(f) of the DMCA.
              It is our policy in appropriate circumstances to disable and/or terminate the accounts of users who are repeat infringers.
              Right of Publicity.
              Please be aware that celebrities, and sometimes others, may have a "right of publicity," which means that they may have a right to control commercial uses of their name, image, likeness, and other aspects of their identity. Although you may be a fan, you risk infringing celebrity rights if you use a celebrity name or likeness on the Websites and you don't have the celebrity's permission. Open Castings reserves the right to remove any Content contained in or posted to the Websites that Open Castings determines in its sole discretion does or may allegedly infringe another person's copyright, trademark, celebrity material or other rights.
              Notices to Open Castings regarding any alleged infringement on the Websites should be directed to Open Castings 's General Counsel's Office at legal@opencastings.com, 212-493-4243.
              9. User Accounts.
              The creation of a User account may be required for the use of certain portions of the Websites (e.g., e-mail, newsletters, competitions, forums, content downloads, and promotions). As part of Open Castings' registration process, you will select a username and password and be asked to submit, among other things, your email address. You agree that all information you provide to Open Castings for purposes of creating a user account (the "User Information") will be true, accurate, current and complete and your failure to provide such information will constitute a breach of these Terms of Use and may result in the immediate termination of your account. All information about you including your User Information, any information obtained by Open Castings as a result of your use of the Websites, and any information stored or transmitted in any way on or through the use of the Websites is subject to Open Castings 's Privacy Policy, which can be found here. Open Castings 's Privacy Policy is incorporated into these Terms of Use by this reference.
              You understand that you may not (i) select or use a name of another person with the intent to impersonate that person; (ii) use the rights of any person without authorization; or (iii) use a name that Open Castings, in its sole discretion, deems inappropriate. You agree that any information that you provide to the Websites, including but not limited to User Information, shall be true and accurate and current, and you are responsible for updating such information to keep it true, accurate and current. If you create a user account with the Websites, you accept responsibility for all activities that occur under your account or password and you agree you will not sell, transfer or assign your user account. You are responsible for maintaining the confidentiality of your password, if any, and for restricting access to your computer so that others may not access any password-protected portion of the Websites (including the Paid Services) using your name, user name or password in whole or in part.
              Each User name permits one person to access the password-protected portion of the Websites (including the Paid Services), and you shall not share the user name and password with any third party. You shall be solely responsible for any and all use of the Websites, including without limitation, any and all charges incurred by a third party, under or using your user name and password. If at any time you should learn or suspect that your password has been compromised, you shall promptly notify Customer Service at 1-917-725-6367 and confirm such notice in writing. Upon receiving such telephonic and written notice, Open Castings will assign a new password to you without charge.
              You agree that any unauthorized use of the Websites (or any Content derived therefrom) by you or by anyone using you user name or password may result in immediate suspension or termination of your user account by Open Castings, in its sole and absolute discretion, without refund of any pre-paid fees. You represent and warrant that the information provided during the subscription process is true and accurate and agrees to update the information thereafter in the event of any changes. Open Castings reserves the right to terminate your access to and use of the Websites in the event that you provide any false information to Open Castings as part of the subscription process, without refund of any pre-paid fees. In the event of such termination, you will continue to be liable for applicable fees for the period prior to termination, together with such other remedies as to which Open Castings may be entitled.
              10. Subscription Terms, Fees and Payments; Automatic Renewal and Cancellation.
              Open Castings offers month-to-month, semi-annual (6 month) and annual (12 month) subscriptions on opencastings.com to all Paid Services.The length of the subscription period is selected by you during the enrollment process.
              All Subscriptions are Automatically Renewing.
              This means that once you become a subscriber, your subscription will be automatically renewed and your credit or debit card will be charged based on the subscription program (annually, semiannually, or monthly) you have chosen unless you opt out or cancel by following the instructions in these Terms of Use. By subscribing to the Paid Services, you authorize Open Castings to charge the applicable recurring subscription fees to your credit or debit card. In some cases, when you subscribe to a free trial of the Paid Services, you will be asked to authorize, and by accepting these Terms of Use you hereby expressly authorize, Open Castings to charge the applicable recurring subscription fees to your credit or debit card upon the expiration of the free trial.
              When you initially subscribe to the Paid Services, your credit or debit card will be charged immediately for the initial term of the subscription at the then-current fee for the applicable subscription period. When you initially subscribe to a free trial of the Paid Services, you will be not charged for the initial term of the free trial. Unless you notify Open Castings of your decision to terminate your subscription or, as applicable, your free trial, your subscription will automatically renew at the end of each subscription term or free trial (if applicable) at the then-current fee.
              You will be charged in advance for the renewal term of the subscription service (or initial term, in the case of a renewal following the expiration of an applicable free trial) on your applicable billing date (the "Billing Date"), which will be the corresponding monthly, semi-annual or annual anniversary of the activation date of your subscription. If, however, the activation date of your subscription (or, as applicable, your free trial) is on the 29th, 30th or 31st day of a month, and your Billing Date does not exist in a particular month because there are fewer than thirty-one (31) days in the month payment is due, your Billing Date for that particular renewal (or initial term, in the case of a renewal following the expiration of an applicable free trial) will be on the last day of the month in which your Billing Date would otherwise be. Each charge on the applicable Billing Date applies to the subscription period immediately following the Billing Date (e.g., a charge for a monthly subscription applies to the month immediately following the Billing Date). You understand that any applicable sales or use taxes will be payable by you, and may be included in each periodic statement.
              Open Castings may, in its sole discretion, suspend access to your account or deactivate your account without notice to you if Open Castings is unable to process your payment or if payment is past due, regardless of the amount. You agree to pay any outstanding balance in full within thirty (30) days of cancellation or termination of your subscription. You may update any of your billing information (including a change to your desired billing payment method) through your account settings on opencastings.com.
              BY COMPLETING THE ENROLLMENT PROCESS, YOU UNDERSTAND AND AGREE THAT UNLESS AND UNTIL YOU CANCEL YOUR SUBSCRIPTION TO THE PAID SERVICES:
              YOUR SUBSCRIPTION TO THE PAID SERVICES WILL AUTOMATICALLY RENEW AT THE END OF THE SUBSCRIPTION PERIOD AND CONTINUE FOR ANOTHER SUBSCRIPTION PERIOD;
              YOU WILL AUTOMATICALLY BE BILLED AT THE START OF EACH NEW SUBSCRIPTION PERIOD; AND
              THAT PERIODIC CHARGES FOR EACH NEW SUBSCRIPTION PERIOD WILL BE AUTOMATICALLY BILLED TO YOUR DESIGNATED BILLING PAYMENT METHOD.
              Opting Out Of Renewal.
              YOU MAY TERMINATE ENROLLMENT IN AUTOMATIC RENEWAL AT ANY TIME BY CONTACTING Open Castings ONLINE, EMAILING CUSTOMERS@opencastings.com, OR CALLING 1-917-725-6367. YOUR SUBSCRIPTION TO THE PAID SERVICES SHALL BE DEEMED TERMINATED ON THE LAST DAY OF THE THEN IN EFFECT SUBSCRIPTION PERIOD. YOU AGREE THAT EXCEPT AS PROVIDED HEREIN, THE SUBSCRIPTION FEE IS NON-REFUNDABLE ONCE PAID.
              Unauthorized Charges.
              YOU ACKNOWLEDGE AND AGREE THAT YOU, AND NOT Open Castings, ARE RESPONSIBLE FOR PAYING ANY AMOUNTS BILLED TO YOUR CREDIT OR DEBIT CARD BY A THIRD PARTY WHICH WERE NOT AUTHORIZED BY YOU.
              Billing Discrepancies.
              Unless you notify Open Castings of any discrepancies within sixty (60) days after they first appear on your payment statement, they will be deemed accepted by you and you release Open Castings from all liabilities and claims of loss resulting from any such error or discrepancy.
              Fees Subject to Change.
              Open Castings may change the fees and charges then in effect by giving you notice in advance or by posting the changed fees online at opencastings.com/subscribe. It is your responsibility to check the current fees.  All fees and charges incurred in connection with your user name(s) and password(s) will be billed to the credit or debit card you designate during the registration process. If you want to designate a different credit or debit card or there is a change in your credit or debit card validity or expiration date, you must call Customer Service at 1-917-725-6367 or update your information through your account settings on opencastings.com.
              Cancellations and Refunds.
              You may cancel a free trial at any time during the free trial period and incur no charge. After the free trial is complete, you will be charged at the rate and schedule selected when you enrolled in the trial. Monthly subscriptions are not eligible for a refund, but can be cancelled to prevent additional future charges. For all initial purchases of subscriptions longer than one month, you may cancel prior to renewal to prevent future renewal charges; or cancel during the first five (5) days after renewal to remain eligible for a full refund on the renewal payment. If your subscription begins with a free trial and converts into an annual subscription, the five day refund period begins once the free trial ends. If the cancellation occurs after the first five days or if the charge was for a monthly subscription, you will not receive a refund. For all renewals of subscriptions longer than one month, you may cancel within five days of the renewal date and receive a full refund; cancellations made after this period are not eligible for a refund. Monthly subscriptions (both initial subscriptions and renewals) may be cancelled at any time but you will not receive a refund. If you cancel your subscription but are not eligible for a refund, you will retain access to the Websites until your subscription expires. Cancellations may be made by filing a customer support ticket atwww.opencastings.com/contact, or by emailing customers@opencastings.com, or by calling customer service at 1-917-725-6367. Your cancellation must be received by end of business (5:00 p.m. Eastern Time) on the appropriate day as described above, or earlier. All refunds will be given to the original credit or debit card on which the purchase was made. Please allow a reasonable time for the refund to reach you or be charged back to your account.
              11. Additional Terms.
              In some instances, additional terms or end user license agreements apply to some services, products, software, competitions or promotions offered via the Websites. Such terms are posted in connection with the applicable service, product, software, competition or promotion and are in addition to these Terms of Use. For example, the Open Castings Message Board service is subject to its own supplemental Terms of Use located atbbs.opencastings.com/eve/tos.  In the event of a conflict, the additional terms prevail over these Terms of Use. Open Castings may change, suspend or discontinue any aspect of the Websites at any time and without prior notice.
              12. Entire Agreement
              You acknowledge and agree that these Terms of Use, the Privacy Policy, any applicable end user license or similar agreements contain the entire agreement between the parties relating to the Websites; provided, however these Terms of Use do not alter in any way the terms or conditions of any other agreement User may have with Open Castings. If any provision in these Terms of Use is invalid or unenforceable under applicable law, that part will be deemed severable and the remaining provisions will continue in full force and effect.  Each Affiliate expressly made a third party beneficiary of this Agreement and may enforce this Agreement directly against you. This Agreement will be binding on and will inure to the benefit of the legal representatives, successors and assigns of the parties hereto
              13. Equipment and Internet Access.
              You understand and agree that you are responsible for providing all telephone, modem, Internet connection, intranet connection, extranet connection and other equipment necessary for you to access the Websites (including the Paid Services). You are solely responsible for and shall bear the costs of any such equipment and any fees or charges incurred to access the Websites (including the Paid Services) through an Internet access provider or other third-party service, including any applicable taxes.
              14. No Oral Agreements or Modifications.
              There shall be no amendment or modification of these Terms of Use unless the same is in writing and signed by an authorized representative of Open Castings. Oral agreements shall expressly be non-binding and unenforceable.
              15. Dispute Resolution.
              Please read this section carefully. It affects rights that you may otherwise have. It provides for resolution of most disputes through arbitration instead of court trials and class actions. Arbitration is final and binding and subject to only very limited review by a court. This arbitration clause shall survive termination of this agreement.
              If a dispute arises between you and Open Castings, our goal is to provide you a neutral and cost effective means of resolving the dispute quickly.
              Negotiations.
              Before initiating any arbitration or court proceeding, you and Open Castings agree to first attempt to negotiate any dispute, controversy or claim related to the Websites, these Terms of Use or the Privacy Policy, whether based in contract, tort, statute, fraud, misrepresentation or any other legal theory (each, a "Claim") (except those Claims expressly provided in Section 17(f) below) informally for at least thirty (30) days. Negotiations will begin upon written notice. Open Castings will send its notice via Certified Mail to your billing or other physical address (if on file with Open Castings) and email you a copy to the email address you have provided. You agree to send your notice via Certified Mail to Open Castings 's General Counsel's Office at the address specified in Section [8] of these Terms of Use and email a copy to legal@opencastings.com.
              Binding Arbitration.
              This Section 17 is referred to in these Terms of Use as the "Arbitration Agreement". You agree that any and all disputes or claims that have arisen or may arise between you and Open Castings or a Open Castings affiliate, whether relating to these Terms of Use (including any alleged breach thereof), or otherwise, shall be resolved exclusively through final and binding arbitration, rather than a court in accordance with the terms of this Arbitration Agreement, except you may assert individual claims in small claims court, if your claims qualify. Your rights will be determined by a neutral arbitrator, not a judge or jury. The Federal Arbitration Act governs the interpretation and enforcement of this Arbitration Agreement.
              Arbitration Procedures.
              The arbitration of any dispute or claim shall be conducted in accordance with the American Arbitration Association ("AAA") as modified by this agreement. The AAA Rules and information about arbitration and fees are available upon request from the AAA (call 1-800-778-7879) or online at adr.org. You and Open Castings agree that the Terms of Use evidences a transaction in interstate commerce and this arbitration provision will be interpreted and enforced in accordance with the U.S. Federal Arbitration Act and federal arbitration law.
              An arbitrator may not award relief in excess of or contrary to what the Terms of Use provides, including Section 18 Limitation on Liability order consolidation or arbitration on a class wide or representative basis, or award punitive damages or any other damages aside from the prevailing party's actual economic damages, except that the arbitrator may award on an individual basis damages expressly required by statute and may order injunctive or declaratory relief pursuant to an applicable consumer protection statute. In any arbitration applying the AAA Rules applicable to large/complex cases, the arbitrator(s) must also apply the Federal Rules of Evidence, and the losing party may have the award reviewed in accordance with the review procedures set forth in the AAA Rules. Any arbitration shall be confidential, and neither you nor we may disclose the existence, content or results of any arbitration, except as may be required by law or for purposes of enforcement of the arbitration award. Judgment on any arbitration award may be entered in any court having proper jurisdiction. If any portion of this arbitration clause is determined by a court to be inapplicable or invalid, than the remainder shall still be given full force and effect.
              As part of the arbitration, both you and we will have the opportunity for discovery of non-privileged information that is relevant to the Claim. The arbitrator will provide a written statement of the arbitrator's decision regarding the Claim, the award given and the arbitrator's findings and conclusions on which the arbitrator's decision is based. The determination of whether a Claim is subject to arbitration shall be governed by the Federal Arbitration Act and determined by a court rather than an arbitrator. Except as otherwise provided in these Terms of Use, (i) you and Open Castings may litigate in court to compel arbitration, stay proceedings pending arbitration, or confirm, modify, vacate or enter judgment on the award entered by the arbitrator; and (ii) the arbitrator's decision will be final, binding on all parties and enforceable in any court that has jurisdiction, provided that any award may be challenged if the arbitrator fails to follow applicable law. BY AGREEING TO THIS ARBITRATION PROVISION, YOU UNDERSTAND THAT YOU AND Open Castings ARE WAIVING THE RIGHT TO SUE IN COURT AND HAVE A JURY TRIAL.
              Arbitration Fees.
              All administrative fees and expenses of arbitration will be divided equally between you and us, except that for claims of less than $500, you will be obligated to pay $25 and we will pay all other administrative costs and fees. In all arbitrations, each party will bear the expense of its own counsel, experts, witnesses and preparation and presentation of evidence at the arbitration.
              Location.
              The arbitration will take place in your hometown area if you so notify Open Castings in your notice of arbitration or within five (5) days following receipt of Open Castings' arbitration notice. In the absence of a notice to conduct the arbitration in your hometown area, the arbitration will be conducted in New York, New York, unless the parties agree to video, phone or Internet connection appearances.
              Prohibition of Class and Representative Actions and Non-Individualized Relief.
              YOU AND Open Castings AGREE THAT ANY ARBITRATION WILL BE LIMITED TO THE CLAIM BETWEEN Open Castings AND YOU INDIVIDUALLY. YOU AND Open Castings AGREE THAT (A) THERE IS NO RIGHT OR AUTHORITY FOR ANY DISPUTE TO BE ARBITRATED ON A CLASS-ACTION BASIS OR TO UTILIZE CLASS ACTION PROCEDURES; (B) THERE IS NO RIGHT OR AUTHORITY FOR ANY DISPUTE TO BE BROUGHT IN A PURPORTED REPRESENTATIVE CAPACITY OR AS A PRIVATE ATTORNEY GENERAL; AND (C) NO ARBITRATION WILL BE JOINED WITH ANY OTHER.
              Exceptions to Negotiations and Arbitration.
              You and Open Castings agree that the following Claims are not subject to the above provisions concerning negotiations and binding arbitration: (i) any Claims seeking to enforce or protect, or concerning the validity of, any of your or Open Castings' intellectual property rights; (ii) any Claim related to, or arising from, allegations of theft, piracy, invasion of privacy or unauthorized use; and (iii) any claim for equitable relief. In addition to the foregoing, either party may assert an individual action in small claims court for Claims that are within the scope of such courts' jurisdiction in lieu of arbitration, provided that any such action or proceeding must be commenced no later than one year after the accrual of the Claim giving rise thereto.
              Severability.
              You and Open Castings agree that if any portion this "Dispute Resolution" section is found illegal or unenforceable, that portion will be severed and the remainder of this section will be given full force and effect. If for any reason the Arbitration Agreement is deemed inapplicable or invalid, you and Open Castings both agree (i) that all Claims will be exclusively decided either the courts of the State of New York situated in the County of New York or in the United States District Court for the Southern District of New York, and you and Open Castings agree to submit to the personal jurisdiction of those courts, and (ii) that you and Open Castings both waive, to the fullest extent allowed by law, any claims to recover punitive or exemplary damages and any right to pursue any claims on a class or consolidated basis or in a representative capacity. By using the Websites, you accept generally and unconditionally the jurisdiction of the aforesaid courts and irrevocably waives any objection to such jurisdiction.
              16. Governing Law, Jurisdiction and Venue.
              All matters related to the Websites and these Terms of Use (in each case, including non-contractual disputes or claims) shall be governed by and construed in accordance with New York law; provided, that the Federal Arbitration Act shall govern the interpretation and enforcement of Section 17. Unless Open Castings and you agree otherwise, in the event that the Arbitration Agreement is deemed inapplicable or invalid, you and Open Castings both agree that all Claims will be exclusively decided by either the courts of the State of New York situated in the County of New York or in the United States District Court for the Southern District of New York, and you and Open Castings agree to submit to the personal jurisdiction of those courts. By using the Websites, you accept generally and unconditionally the jurisdiction of the aforesaid courts and irrevocably waives any objection to such jurisdiction.
              17.Recovery of Fees.
              You agree that if Open Castings takes action (by itself or through its representatives) to enforce any of the provisions of these Terms of Use against you, including collection of any amounts due to Open Castings, Open Castings shall be entitled to recover from you (and you agree to pay), Open Castings' reasonable and necessary attorney's fees and any costs of any litigation, in addition to all sums to which Open Castings is entitled or any other relief, at law or in equity, except as otherwise limited herein.
              18. Limitation of Liability.
              Incidental Damages and Aggregate Liability.
              In no event will Open Castings and ITS AFFILIATES be liable for any indirect, special, incidental, or consequential damages, losses or expenses arising out of or relating to the use or inability to use the Websites, including without limitation damages related to any information received from the Websites, removal of content from the Websites, including profile information, any email distributed to any User or any linked web site or use thereof or inability to use by any party, or in connection with any termination of your subscription or ability to access the Websites, failure of performance, error, omission, interruption, defect, delay in operation or transmission, computer virus or line or system failure, even if Open Castings, or representatives thereof, are advised of the possibility of such damages, losses or expenses. UNDER NO CIRCUMSTANCES WILL Open Castings' AGGREGATE LIABILITY, IN ANY FORM OF ACTION WHATSOEVER IN CONNECTION WITH THIS AGREEMENT OR THE USE OF THE WEBSITES, EXCEED THE PRICE PAID BY YOU FOR YOUR ACCOUNT IN THE 12 MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO SUCH CLAIM, OR, IF YOU HAVE NOT PAID Open Castings FOR THE USE OF ANY SERVICES, THE AMOUNT OF $25.00 OR ITS EQUIVALENT.
              No Liability for non-Open Castings Actions.
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL Open Castings BE LIABLE FOR ANY DAMAGES WHATSOEVER, WHETHER DIRECT, INDIRECT, GENERAL, SPECIAL, COMPENSATORY, AND/OR CONSEQUENTIAL, ARISING OUT OF OR RELATING TO THE CONDUCT OF YOU OR ANYONE ELSE IN CONNECTION WITH THE USE OF THE SITE OR THE SERVICES, INCLUDING WITHOUT LIMITATION, BODILY INJURY, EMOTIONAL DISTRESS, AND/OR ANY OTHER DAMAGES RESULTING FROM ANYONE'S RELIANCE ON INFORMATION OR OTHER CONTENT POSTED ON THE SITE, OR TRANSMITTED TO OR BY ANY USERS OR ANY OTHER INTERACTIONS WITH OTHER REGISTERED USERS OF THE SITE OR SERVICES, WHETHER ONLINE OR OFFLINE. THIS INCLUDES ANY CLAIMS, LOSSES OR DAMAGES ARISING FROM THE CONDUCT OF USERS WHO HAVE REGISTERED UNDER FALSE PRETENSES OR WHO ATTEMPT TO DEFRAUD OR HARM YOU.
              In addition to the preceding paragraphs of this section and other provisions of these Terms of Use, any advice that may be posted on the Websites is for informational purposes only and is not intended to replace or substitute for any professional financial, medical, legal, or other advice. Open Castings makes no representations or warranties and expressly disclaims any and all liability concerning any treatment, action by, or effect on any person following the information offered or provided within or through the Websites. If you have specific concerns or a situation arises in which you require professional advice, you should consult with an appropriately trained and qualified specialist.
              19. Indemnity.
              You agree to and shall defend, indemnify and hold harmless Open Castings, its affiliates and its and its affiliates’ directors, officers, employees, agents, representatives, members, joint venturers, licensors, suppliers, vendors, distributors, advertisers and other contracting parties (hereinafter “Affiliates”) from and against any and all claims, losses, expenses, including reasonable legal fees or demands of liability, including reasonable attorneys' fees and costs incurred by Open Castings and its affiliates in connection with any claim by a third party (including an intellectual property claim) arising out of (i) materials and content you submit, post or transmit through the Websites, or (ii) use of the Websites by you in violation of these Terms of Use or in violation of any applicable law. Users further agree that they will cooperate as reasonably required in the defense of such claims. Open Castings and its Affiliates reserve the right, at their own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by Users, and Users shall not, in any event, settle any claim or matter without the written consent of Open Castings. Users further agree to hold harmless Open Castings and its Affiliates from any claim arising from a third party's use of information or materials of any kind that Users post to the Websites.
              20. Disclaimers of Warranty.
              THE WEBSITES (INCLUDING THE PAID SERVICES) AND ALL CONTENT PROVIDED THROUGH THE SAME ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT ANY WARRANTY OR CONDITION, EXPRESS OR IMPLIED. TO THE MAXIMUM EXTENT PERMISSIBLE UNDER APPLICABLE LAW, Open Castings, AND EACH OF ITS AFFILIATES, SPECIFICALLY DISCLAIM ALL IMPLIED WARRANTIES INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF TITLE, QUALITY, PERFORMANCE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. FURTHER, NO WARRANTIES WILL BE IMPLIED BY ANY COURSE OF DEALING OR COURSE OF PERFORMANCE.
              YOU ACKNOWLEDGE THAT ALL INFORMATION AND SERVICES PROVIDED IN CONNECTION WITH THE WEBSITES ARE COMPILED FROM AND DISTRIBUTED BY SOURCES THAT ARE OFTEN BEYOND THE CONTROL OF Open Castings. Open Castings MAKES NO REPRESENTATION OR WARRANTY THAT (I) THE WEBSITES WILL MEET YOUR EXPECTATIONS OR REQUIREMENTS, (II) THE WEBSITES WILL BE AVAILABLE, UNINTERRUPTED, TIMELY, SECURE, ACCURATE, COMPLETE OR ERROR-FREE, (III) ANY RESULTS OR INFORMATION THAT MAY BE OBTAINED FROM THE USE OF THE WEBSITES WILL BE ACCURATE, TIMELY, COMPLETE OR RELIABLE, (IV) ANY ERRORS OR DEFECTS IN THE WEBSITES WILL BE CORRECTED, OR (V) THE WEBSITES, NETWORKS OR SERVERS THAT MAKE THE WEBSITES AVAILABLE ARE FREE OF VIRUSES, CLOCKS, TIMERS, COUNTERS, WORMS, SOFTWARE LOCKS, TROJAN HORSES, TRAP DOORS, TIME BOMBS OR ANY OTHER HARMFUL CODES, INSTRUCTIONS, PROGRAMS OR COMPONENTS. OPERATION OF THE WEBSITES MAY BE INTERFERED WITH BY NUMEROUS FACTORS OUTSIDE OF Open Castings' CONTROL INCLUDING, BUT NOT LIMITED TO, TELECOMMUNICATIONS NETWORK DISRUPTIONS. Open Castings IS NOT RESPONSIBLE AND WILL HAVE NO LIABILITY FOR ANY FAILURES OF THE INTERNET OR ANY DATA OR TELECOMMUNICATIONS EQUIPMENT, SYSTEM OR NETWORK USED IN CONNECTION WITH THE WEBSITES. YOU ACKNOWLEDGE THAT THE ENTIRE RISK ARISING OUT OF THE USE, INABILITY TO USE OR PERFORMANCE OF ANY OF THE WEBSITES REMAINS WITH YOU TO THE MAXIMUM EXTENT PERMISSIBLE UNDER LAW. YOU ACKNOWLEDGE AND AGREE THAT YOUR SOLE REMEDY FOR ANY PROBLEMS OR DISSATISFACTION WITH THE WEBSITES (INCLUDING THE PAID SERVICES) IS TO TERMINATE YOUR ACCOUNT AND DISCONTINUE USE OF THE WEBSITES.
              22. Contact Information.
              If you have any questions about these Terms of Use or your rights or Open Castings' obligations relating to the Websites or the Paid Services, please email us at legal@opencastings.com or you may contact us by mail at:
                Open Castings, LLC
                Attn: General Counsel's Office
                  45 Main St.
                  Brooklyn, NY 11201
          </p>
        </Paper>
      </div>
    );
  }
}
